apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: todo-backend
        imagePullPolicy: Never # Використовуємо локальний образ
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/todo_db"
        ports:
        - containerPort: 8000